-- 회원별 "재구매"한 상품들의 ID는? -> 유저 ID랑 상품 ID가 일치하는 행들끼리 묶어야된다.
# SELECT *, SUM(SALES_AMOUNT) over (partition by USER_ID GROUP BY PRODUCT_ID) CNT
# FROM ONLINE_SALE

SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID HAVING COUNT(*) > 1
ORDER BY USER_ID, PRODUCT_ID DESC

# SELECT *
# FROM ONLINE_SALE
# ORDER BY USER_ID, PRODUCT_ID