--  자동차들의 정보를 담은 "CAR_RENTAL_COMPANY_CAR"
--  대여 기록 정보를 담은 "CAR_RENTAL_COMPANY_RENTAL_HISTORY"
--  자동차 종류 별 대여 기간 종류 별 할인 정책 정보를 담은 "CAR_RENTAL_COMPANY_DISCOUNT_PLAN"
--  자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 "2022년 11월 1일부터 2022년 11월 30일까지" 대여 가능하고 "30일간의 대여 금액이 50만원 이상 200만원 미만"인 자동차

# WITH CS AS(
#     SELECT C.*, H.END_DATE, H.START_DATE
#     FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
#     WHERE C.CAR_TYPE IN ('세단', 'SUV')
#     GROUP BY C.CAR_ID HAVING (H.END_DATE NOT BETWEEN DATE('2022-11-01') AND DATE('2022-11-30')) 
#                          AND NOT (H.START_DATE < DATE('2022-11-01') AND H.END_DATE >= DATE('2022-12-01'))
# ), PLAN AS (
#     SELECT *
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
#     WHERE duration_type = "30일 이상"
# )

# SELECT CS.CAR_ID, CS.CAR_TYPE, CAST(daily_fee*30*(1 - DISCOUNT_RATE / 100) AS DECIMAL) FEE
# FROM CS INNER JOIN PLAN ON CS.CAR_TYPE = PLAN.CAR_TYPE
# GROUP BY CS.CAR_ID HAVING FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, CS.CAR_TYPE ASC, CS.CAR_ID DESC

SELECT D.CAR_ID, D.CAR_TYPE, CAST(D.DAILY_FEE * (1 -(C.DISCOUNT_RATE * 0.01)) * 30 AS SIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
INNER JOIN (SELECT DISTINCT B.CAR_ID, B.DAILY_FEE, B.CAR_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A   
RIGHT OUTER JOIN CAR_RENTAL_COMPANY_CAR  AS B
ON A.CAR_ID = B.CAR_ID
WHERE (B.CAR_TYPE IN ('SUV','세단'))
AND (A.START_DATE IS NULL) OR B.CAR_ID NOT IN (select CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01'
    AND START_DATE < '2022-12-01') ) AS D
ON C.CAR_TYPE  = D.CAR_TYPE
WHERE C.DURATION_TYPE like ("%30%")
AND D.DAILY_FEE * (1 -(C.DISCOUNT_RATE * 0.01)) *30 >= 500000
AND D.DAILY_FEE * (1 -(C.DISCOUNT_RATE * 0.01)) *30 < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;