--  자동차들의 정보를 담은 "CAR_RENTAL_COMPANY_CAR"
--  대여 기록 정보를 담은 "CAR_RENTAL_COMPANY_RENTAL_HISTORY"
--  자동차 종류 별 대여 기간 종류 별 할인 정책 정보를 담은 "CAR_RENTAL_COMPANY_DISCOUNT_PLAN"
--  자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 "2022년 11월 1일부터 2022년 11월 30일까지" 대여 가능하고 "30일간의 대여 금액이 50만원 이상 200만원 미만"인 자동차

WITH CANT_RENT AS(
    SELECT C.*, START_DATE, END_DATE
    FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    WHERE (START_DATE BETWEEN DATE('2022-11-01') AND DATE('2022-11-30')) OR
          (END_DATE BETWEEN DATE('2022-11-01') AND DATE('2022-11-30')) OR
          (START_DATE < DATE('2022-11-01') AND END_DATE >= DATE('2022-12-01'))
), PLAN AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    WHERE duration_type = "30일 이상"
)

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE*30*(1-DISCOUNT_RATE/100),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN PLAN ON C.CAR_TYPE = PLAN.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV') AND 
      C.CAR_ID NOT IN (SELECT CAR_ID FROM CANT_RENT) AND
      ROUND(DAILY_FEE*30*(1-DISCOUNT_RATE/100),0) >= 500000 AND
      ROUND(DAILY_FEE*30*(1-DISCOUNT_RATE/100),0) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC

# SELECT CS.CAR_ID, CS.CAR_TYPE, CAST(daily_fee*30*(1 - DISCOUNT_RATE / 100) AS DECIMAL) FEE
# FROM CS INNER JOIN PLAN ON CS.CAR_TYPE = PLAN.CAR_TYPE
# GROUP BY CS.CAR_ID HAVING FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, CS.CAR_TYPE ASC, CS.CAR_ID DESC

# SELECT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE*30*(1-DISCOUNT_RATE/100),0) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR C
# JOIN (SELECT CAR_TYPE, DISCOUNT_RATE
#       FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#       WHERE DURATION_TYPE = '30일 이상'
#      ) D
# ON C.CAR_TYPE = D.CAR_TYPE
# WHERE (C.CAR_TYPE = 'SUV' OR C.CAR_TYPE = '세단') AND 
# ROUND(DAILY_FEE*30*(1-DISCOUNT_RATE/100),0) >= 500000 AND
# ROUND(DAILY_FEE*30*(1-DISCOUNT_RATE/100),0) <= 2000000 AND
# CAR_ID NOT IN (SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE BETWEEN '2022-11-01' AND '2022-12-01'
# OR END_DATE BETWEEN '2022-11-01' AND '2022-12-01')
# ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC