-- 코드를 작성해주세요
WITH D AS (
    SELECT *, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) RNK
    FROM ECOLI_DATA
)

SELECT ID, 
    CASE
        WHEN RNK / (SELECT COUNT(*) FROM D) <= 0.25 THEN 'CRITICAL'
        WHEN RNK / (SELECT COUNT(*) FROM D) <= 0.50 THEN 'HIGH'
        WHEN RNK / (SELECT COUNT(*) FROM D) <= 0.75 THEN 'MEDIUM'
        WHEN RNK / (SELECT COUNT(*) FROM D) <= 1 THEN 'LOW'
        ELSE NULL
    END COLONY_NAME
FROM D
ORDER BY ID
