-- 코드를 작성해주세요
WITH D AS (
    SELECT *, CUME_DIST() OVER (ORDER BY SIZE_OF_COLONY DESC) ACCU
    FROM ECOLI_DATA
)

SELECT ID, 
    CASE
        WHEN ACCU <= 0.25 THEN 'CRITICAL'
        WHEN ACCU <= 0.50 THEN 'HIGH'
        WHEN ACCU <= 0.75 THEN 'MEDIUM'
        WHEN ACCU <= 1 THEN 'LOW'
        ELSE NULL
    END COLONY_NAME
FROM D
ORDER BY ID