-- 중고 거래 게시물을 "3건 이상 등록"한 사용자는?
SELECT U.USER_ID, U.NICKNAME, CONCAT_WS(' ', U.CITY, U.STREET_ADDRESS1, U.STREET_ADDRESS2) 전체주소, 
                                CONCAT_WS('-', SUBSTR(TLNO, 1, 3), SUBSTR(TLNO, 4, 4), SUBSTR(TLNO, 8, 4)) 전화번호
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY B.WRITER_ID HAVING COUNT(*) >= 3
ORDER BY U.USER_ID DESC

# SELECT *, COUNT(*)
# FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
# GROUP BY B.WRITER_ID HAVING COUNT(*) >= 3