-- "년", "월", "성별" 별로 상품을 구매한 "회원수"를 입력하세요
# SELECT YEAR(SALE.SALES_DATE) YEAR, MONTH(SALE.SALES_DATE) MONTH, INFO.GENDER GENDER, COUNT(SALE.USER_ID) USERS
# FROM USER_INFO INFO INNER JOIN ONLINE_SALE SALE ON INFO.USER_ID = SALE.USER_ID
# WHERE INFO.GENDER IS NOT NULL
# GROUP BY YEAR(SALE.SALES_DATE), MONTH(SALE.SALES_DATE), INFO.GENDER
# ORDER BY YEAR, MONTH, GENDER

SELECT 
    YEAR(SALE.SALES_DATE) AS SALE_YEAR, 
    MONTH(SALE.SALES_DATE) AS SALE_MONTH, 
    INFO.GENDER AS GENDER, 
    COUNT(DISTINCT INFO.USER_ID) AS USERS
FROM 
    USER_INFO INFO 
INNER JOIN 
    ONLINE_SALE SALE 
ON 
    INFO.USER_ID = SALE.USER_ID
WHERE 
    INFO.GENDER IS NOT NULL
GROUP BY 
    SALE_YEAR, SALE_MONTH, INFO.GENDER
ORDER BY 
    SALE_YEAR, SALE_MONTH, GENDER;
