-- "입양 데이터가 있고", "들어온 기록이 없는" 동물은?
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_INS INS RIGHT JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID 
WHERE INS.DATETIME IS NULL
ORDER BY OUTS.ANIMAL_ID