-- 코드를 작성해주세요
WITH RECURSIVE XX AS (
    -- 루트 노드부터 시작
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL 
    
    -- 자식 노드를 재귀적으로 연결
    SELECT D.ID, D.PARENT_ID, XX.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA D INNER JOIN XX ON D.PARENT_ID = XX.ID
)

# SELECT COUNT(*) COUNT, GENERATION 
# FROM XX
# GROUP BY GENERATION 
# ORDER BY GENERATION 

SELECT COUNT(*) COUNT, GENERATION 
FROM XX
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM XX WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION 
ORDER BY GENERATION 