-- "2022년 4월 13"일 "취소되지 않은" "흉부외과(CS) 진료" 예약 내역은?
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A INNER JOIN PATIENT P ON A.PT_NO = P.PT_NO 
                   INNER JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE YEAR(A.APNT_YMD) = 2022 AND MONTH(A.APNT_YMD) = 4 AND DAY(A.APNT_YMD) = 13
      AND A.APNT_CNCL_YMD IS NULL 
      AND A.MCDP_CD = "CS"
ORDER BY A.APNT_YMD ASC