SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME 
FROM DEVELOPERS D 
INNER JOIN SKILLCODES C 
ON (COALESCE(D.SKILL_CODE, 0) & COALESCE(C.CODE, 0)) > 0
WHERE C.CATEGORY = 'Front End'
ORDER BY D.ID