-- 사원별 성과금 정보
WITH AVG_GRADE AS(
    SELECT EMP_NO, AVG(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT E.EMP_NO, E.EMP_NAME, 
    CASE
        WHEN G.SCORE >= 96 THEN 'S'
        WHEN G.SCORE >= 90 THEN 'A'
        WHEN G.SCORE >= 80 THEN 'B'
        ELSE 'C'
    END GRADE,
    CASE
        WHEN G.SCORE >= 96 THEN E.SAL * 0.2
        WHEN G.SCORE >= 90 THEN E.SAL * 0.15
        WHEN G.SCORE >= 80 THEN E.SAL * 0.1
        ELSE 0
    END BONUS
FROM HR_EMPLOYEES E INNER JOIN AVG_GRADE G ON E.EMP_NO = G.EMP_NO
ORDER BY E.EMP_NO ASC