-- 아이템의 희귀도가 'RARE'인 아이템들의 모든 다음 업그레이드 아이템

WITH RARE_ITEM AS (
    SELECT *
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)

SELECT  I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM (SELECT * FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL) T INNER JOIN RARE_ITEM R ON T.PARENT_ITEM_ID = R.ITEM_ID                                                                 INNER JOIN ITEM_INFO I ON T.ITEM_ID = I.ITEM_ID
ORDER BY I.ITEM_ID DESC