-- "2022년 8월~2022년 10월" "총 대여 횟수가 5회 이상"인 자동차들의 월별 대여 횟수
# SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE BETWEEN DATE("2022-08-01") AND DATE("2022-10-31")
# GROUP BY CAR_ID, MONTH(START_DATE) HAVING COUNT(*) > 0
# ORDER BY MONTH ASC, CAR_ID DESC

SELECT 
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    START_DATE BETWEEN DATE('2022-08-01') AND DATE('2022-10-31')
    AND CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN DATE('2022-08-01') AND DATE('2022-10-31')
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    )
GROUP BY 
    MONTH(START_DATE), CAR_ID
ORDER BY 
    MONTH ASC, CAR_ID DESC;
