-- 분화된 연도(YEAR), 분화된 연도별 대장균 크기의 편차
WITH YEAR_BIG AS (
    SELECT MAX(SIZE_OF_COLONY) MAX_SIZE, YEAR(DIFFERENTIATION_DATE) YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT Y.YEAR, (Y.MAX_SIZE - E.SIZE_OF_COLONY) YEAR_DEV, E.ID
FROM ECOLI_DATA E INNER JOIN YEAR_BIG Y ON YEAR(E.DIFFERENTIATION_DATE) = Y.YEAR
ORDER BY Y.YEAR ASC, YEAR_DEV ASC