-- "총 주문량이 3000보다 높고", 주 성분이 "과일"인 아이스크림들은?
SELECT I.FLAVOR
FROM FIRST_HALF H INNER JOIN ICECREAM_INFO I ON H.FLAVOR = I.FLAVOR
WHERE H.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY H.TOTAL_ORDER DESC