-- "세단" 자동차들 중 "10월"에 "대여를 시작"한 자동차는?
SELECT DISTINCT CAR.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR CAR INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS ON CAR.CAR_ID = HIS.CAR_ID
WHERE CAR.CAR_TYPE = '세단' AND MONTH(HIS.START_DATE) = 10
ORDER BY CAR.CAR_ID DESC