-- 물고기 종류 별로 가장 큰 물고기
WITH FISH_RNK AS (
    SELECT *, RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) RNK
    FROM FISH_INFO
)

SELECT R.ID, I.FISH_NAME, R.LENGTH
FROM FISH_NAME_INFO I INNER JOIN FISH_RNK R ON I.FISH_TYPE = R.FISH_TYPE
WHERE R.RNK = 1
ORDER BY R.ID ASC