-- 2022년도 한해 평가 점수가 가장 높은 사원 정보를 조회

WITH SUM_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) SCORE 
    FROM HR_GRADE 
    WHERE YEAR = 2022    
    GROUP BY EMP_NO
)

SELECT S.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E INNER JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
                    INNER JOIN SUM_SCORE S     ON E.EMP_NO = S.EMP_NO
WHERE S.SCORE = (SELECT MAX(SCORE) FROM SUM_SCORE)


