-- 부서별 평균 연봉
WITH S AS (
    SELECT DEPT_ID, ROUND(AVG(SAL), 0) AVG_SAL
    FROM HR_EMPLOYEES E
    GROUP BY DEPT_ID
)

SELECT D.DEPT_ID, D.DEPT_NAME_EN, S.AVG_SAL
FROM HR_DEPARTMENT D INNER JOIN S ON D.DEPT_ID = S.DEPT_ID
ORDER BY S.AVG_SAL DESC