-- "조회수가 가장 높은" 중고거래 게시물에 대한 "첨부파일 경로"
SELECT CONCAT_WS('/', '', 'home', 'grep', 'src', F.BOARD_ID, CONCAT(F.FILE_ID, F.FILE_NAME, F.FILE_EXT)) FILE_PATH
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC