-- 평균 길이가 33cm 이상인 물고기들을 종류별로 분류 (단, 10CM 이하의 물고기들은 10CM로 취급)
WITH G_FISH_INFO AS (
    SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE, SUM(IF(LENGTH IS NULL, 10, LENGTH)) SUM_LEN
    FROM FISH_INFO I
    GROUP BY FISH_TYPE
)

SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM G_FISH_INFO
WHERE SUM_LEN / FISH_COUNT >= 33
ORDER BY FISH_TYPE ASC

